### PR TITLE
Scoring gameplay

### PR DESCRIPTION
**Pull request by Rachella**
Think I'll be getting rid of the 'accordion' function to get around an issue with generating random questions (the same question shows on every pane) and for better UI purpose. Still need to figure out the if statement to generate the scoring as well as how to clear the appended players from previous round.

### CODE REVIEW

**Comment by h8rry** [comment]
You should separate your JS with HTML.

Here, you can see that I have only used jQuery in **one** place throughout the whole JS file

``` js
var Game = function () {

};

game = new Game();

var rand = function (min, max) {
  return Math.floor(Math.random() * max) + min;
};

game.questions = [
  {
    title: "Just Ducky",
    possibleAnswers: ["Calm on the surface, paddling like crazy beneath", "Acting like a duck", "Fine and dandy - like Donald"],
    correctAnswer: "Calm on the surface, paddling like crazy beneath",
    score: 10
  }
  // more questions
];

game.selectRandomQuestion = function () {
  var randomIndex = rand(0, this.questions.length);
  return this.questions[randomIndex];
}

game.validateAnswer = function (question, userAnswer) {
  return question.correctAnswer === userAnswer;
}

console.log(game.questions);

var randomQuestion = game.selectRandomQuestion();
console.log(randomQuestion);

var userAnswer = "Calm on the surface, paddling like crazy beneath"; // Here, you can just jQuery to grab the answer
console.log(game.validateAnswer(randomQuestion, userAnswer));
```

**Comment by Rachella** [comment]
okay, I see. I'll amend according to your code above. Thanks!

**Comment by h8rry** [comment]
Thanks!

**Comment by Rachella** [comment]
I updated the code - still having trouble with the function to ensure that players don't answer a previously answered question.  Where would I put the code for alternating scoring? So far it adds up to one score only...

**Comment by h8rry** [comment]
You can add a `answered` field in `game.questions`

**Comment by h8rry** [comment]
For example,

``` js
  {
    title: "Just Ducky",
    possibleAnswers: ["Calm on the surface, paddling like crazy beneath", "Acting like a duck", "Fine and dandy - like Donald"],
    correctAnswer: "Calm on the surface, paddling like crazy beneath",
    score: 10,
    answered: false
  }
```

**Comment by h8rry** [comment]
Looks good

**Pull request merged**
